"""
Clinical availability metrics engine.

Implements the five clinical availability (CA) metrics that quantify how
well each architecture serves clinical needs:

    CA-1  Alert delivery rate
    CA-2  Alert acknowledged before burn rate
    CA-3  Historical data availability
    CA-4  Care continuity (provider transition coverage)
    CA-5  Emergency data availability

Also provides a burn-window sweep utility to find the minimum burn window
that achieves a target CA-2 rate given realistic clinician response-time
distributions.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any

import numpy as np
from scipy.stats import lognorm


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_EPS = 1e-12  # avoid zero-division


# ---------------------------------------------------------------------------
# Internal event log
# ---------------------------------------------------------------------------


@dataclass
class _AlertEvent:
    """Internal record of an alert lifecycle event."""
    generated_at: float = 0.0
    delivered: bool = False
    delivered_at: float | None = None
    acked: bool = False
    acked_at: float | None = None
    acked_before_burn: bool = False
    burn_deadline_s: float | None = None


@dataclass
class _QueryEvent:
    """Internal record of a data query."""
    timestamp_s: float = 0.0
    query_type: str = ""  # 'historical', 'emergency'
    answered: bool = False


@dataclass
class _TransitionEvent:
    """Internal record of a provider transition."""
    timestamp_s: float = 0.0
    data_available: bool = False


# ---------------------------------------------------------------------------
# Monitor
# ---------------------------------------------------------------------------


class ClinicalAvailabilityMonitor:
    """Tracks all five clinical-availability metrics.

    Counters are incremented via ``record_*`` methods; metric values are
    retrieved via ``get_ca*`` methods.  All metrics are rates in [0, 1].
    """

    def __init__(self) -> None:
        # CA-1 counters
        self._alerts_generated: int = 0
        self._alerts_delivered: int = 0

        # CA-2 counters
        self._alerts_for_burn_tracking: int = 0
        self._alerts_acked_before_burn: int = 0

        # CA-3 counters
        self._historical_queries: int = 0
        self._historical_queries_answered: int = 0

        # CA-4 counters
        self._provider_transitions: int = 0
        self._provider_transitions_with_data: int = 0

        # CA-5 counters
        self._emergency_queries: int = 0
        self._emergency_queries_answered: int = 0

        # Detailed logs (for time-series analysis)
        self._alert_log: list[_AlertEvent] = []
        self._query_log: list[_QueryEvent] = []
        self._transition_log: list[_TransitionEvent] = []

    # ------------------------------------------------------------------
    # Recording methods
    # ------------------------------------------------------------------

    def record_alert_generated(self, timestamp_s: float = 0.0) -> None:
        """Record that a clinical alert was generated by the device."""
        self._alerts_generated += 1
        self._alert_log.append(_AlertEvent(generated_at=timestamp_s))

    def record_alert_delivered(self, timestamp_s: float = 0.0) -> None:
        """Record that an alert was successfully delivered to the clinician.

        Should be called after ``record_alert_generated`` for the same alert.
        """
        self._alerts_delivered += 1
        # Update the most recent undelivered alert in the log
        for event in reversed(self._alert_log):
            if not event.delivered:
                event.delivered = True
                event.delivered_at = timestamp_s
                break

    def record_alert_acked_before_burn(
        self,
        acked: bool,
        acked_at: float = 0.0,
        burn_deadline_s: float | None = None,
    ) -> None:
        """Record whether an alert was acknowledged before its data was burned.

        Parameters
        ----------
        acked:
            ``True`` if the clinician acknowledged before the burn timer
            expired; ``False`` otherwise.
        acked_at:
            Timestamp of the acknowledgement (or attempted ack).
        burn_deadline_s:
            The timestamp at which the data would have been burned.
        """
        self._alerts_for_burn_tracking += 1
        if acked:
            self._alerts_acked_before_burn += 1

        # Update log
        for event in reversed(self._alert_log):
            if event.delivered and not event.acked:
                event.acked = True
                event.acked_at = acked_at
                event.acked_before_burn = acked
                event.burn_deadline_s = burn_deadline_s
                break

    def record_historical_query(self, answered: bool, timestamp_s: float = 0.0) -> None:
        """Record a historical-data query and whether it could be answered.

        Parameters
        ----------
        answered:
            ``True`` if the requested historical data was available;
            ``False`` if it had been burned or was otherwise unavailable.
        timestamp_s:
            Simulation time of the query.
        """
        self._historical_queries += 1
        if answered:
            self._historical_queries_answered += 1
        self._query_log.append(_QueryEvent(
            timestamp_s=timestamp_s,
            query_type="historical",
            answered=answered,
        ))

    def record_provider_transition(
        self,
        data_available: bool,
        timestamp_s: float = 0.0,
    ) -> None:
        """Record a care-provider transition event.

        Parameters
        ----------
        data_available:
            ``True`` if the new provider received adequate data to
            continue care without information gaps.
        timestamp_s:
            Simulation time of the transition.
        """
        self._provider_transitions += 1
        if data_available:
            self._provider_transitions_with_data += 1
        self._transition_log.append(_TransitionEvent(
            timestamp_s=timestamp_s,
            data_available=data_available,
        ))

    def record_emergency_query(self, answered: bool, timestamp_s: float = 0.0) -> None:
        """Record an emergency-data query.

        Parameters
        ----------
        answered:
            ``True`` if emergency-relevant data was available.
        timestamp_s:
            Simulation time.
        """
        self._emergency_queries += 1
        if answered:
            self._emergency_queries_answered += 1
        self._query_log.append(_QueryEvent(
            timestamp_s=timestamp_s,
            query_type="emergency",
            answered=answered,
        ))

    # ------------------------------------------------------------------
    # Metric retrieval
    # ------------------------------------------------------------------

    def get_ca1(self) -> float:
        """CA-1: Alert delivery rate = delivered / generated.

        Returns 1.0 if no alerts have been generated (vacuously true).
        """
        if self._alerts_generated == 0:
            return 1.0
        return self._alerts_delivered / self._alerts_generated

    def get_ca2(self) -> float:
        """CA-2: Alert ack-before-burn rate.

        The fraction of alerts where the clinician acknowledged receipt
        before the burn timer expired.  Returns 1.0 if no alerts have
        been tracked for burn behavior.
        """
        if self._alerts_for_burn_tracking == 0:
            return 1.0
        return self._alerts_acked_before_burn / self._alerts_for_burn_tracking

    def get_ca3(self) -> float:
        """CA-3: Historical data availability.

        Fraction of historical queries that could be fully answered.
        Returns 1.0 if no queries have been issued.
        """
        if self._historical_queries == 0:
            return 1.0
        return self._historical_queries_answered / self._historical_queries

    def get_ca4(self) -> float:
        """CA-4: Care continuity across provider transitions.

        Fraction of provider transitions where the new provider had
        adequate data.  Returns 1.0 if no transitions have occurred.
        """
        if self._provider_transitions == 0:
            return 1.0
        return self._provider_transitions_with_data / self._provider_transitions

    def get_ca5(self) -> float:
        """CA-5: Emergency data availability.

        Fraction of emergency queries that were answered.
        Returns 1.0 if no emergency queries have been issued.
        """
        if self._emergency_queries == 0:
            return 1.0
        return self._emergency_queries_answered / self._emergency_queries

    def get_all_metrics(self) -> dict[str, Any]:
        """Return all five CA metrics and underlying counts.

        Returns
        -------
        dict
            Keys: ``ca1`` through ``ca5``, plus ``counts`` sub-dict with
            raw numerator/denominator values.
        """
        return {
            "ca1": round(self.get_ca1(), 6),
            "ca2": round(self.get_ca2(), 6),
            "ca3": round(self.get_ca3(), 6),
            "ca4": round(self.get_ca4(), 6),
            "ca5": round(self.get_ca5(), 6),
            "counts": {
                "alerts_generated": self._alerts_generated,
                "alerts_delivered": self._alerts_delivered,
                "alerts_for_burn_tracking": self._alerts_for_burn_tracking,
                "alerts_acked_before_burn": self._alerts_acked_before_burn,
                "historical_queries": self._historical_queries,
                "historical_queries_answered": self._historical_queries_answered,
                "provider_transitions": self._provider_transitions,
                "provider_transitions_with_data": self._provider_transitions_with_data,
                "emergency_queries": self._emergency_queries,
                "emergency_queries_answered": self._emergency_queries_answered,
            },
        }

    # ------------------------------------------------------------------
    # Burn-window sweep for CA-2 optimization
    # ------------------------------------------------------------------

    def find_minimum_burn_window(
        self,
        target_ca2: float,
        clinician_latency_params: dict[str, float],
        burn_windows: list[float],
        n_simulations: int = 10_000,
        rng_seed: int | None = None,
    ) -> float | None:
        """Find the minimum burn window that achieves a target CA-2 rate.

        Simulates clinician acknowledgement latencies drawn from a
        log-normal distribution and sweeps candidate burn windows to find
        the smallest one where the expected CA-2 >= *target_ca2*.

        Parameters
        ----------
        target_ca2:
            Desired CA-2 rate (e.g. ``0.95`` for 95%).
        clinician_latency_params:
            Parameters for the clinician response-time distribution:
            ``{'median_hours': float, 'sigma': float}``.
            The log-normal is parameterised so that the median response
            time equals ``median_hours`` and the shape parameter is
            ``sigma`` (log-space standard deviation).
        burn_windows:
            Candidate burn windows in seconds, e.g.
            ``[3600, 7200, 14400, 43200, 86400, 172800, 259200]``.
            Must be sorted ascending.
        n_simulations:
            Number of Monte-Carlo samples per burn window.
        rng_seed:
            Optional seed for reproducibility.

        Returns
        -------
        float or None
            The minimum burn window (in seconds) that achieves the target,
            or ``None`` if none of the candidates suffice.
        """
        rng = np.random.default_rng(rng_seed)

        median_hours = clinician_latency_params.get("median_hours", 4.0)
        sigma = clinician_latency_params.get("sigma", 0.8)

        # Log-normal parameterisation: median = exp(mu), so mu = ln(median)
        median_s = median_hours * 3600.0
        mu = np.log(median_s + _EPS)

        # Sample clinician response times (in seconds)
        # scipy lognorm: X ~ lognorm(s=sigma, scale=exp(mu))
        latencies = lognorm.rvs(s=sigma, scale=np.exp(mu), size=n_simulations, random_state=rng)

        sorted_windows = sorted(burn_windows)

        for window_s in sorted_windows:
            # For each sample, alert is acked before burn if latency < window
            acked_fraction = float(np.mean(latencies < window_s))
            if acked_fraction >= target_ca2:
                return window_s

        return None

    def sweep_burn_windows(
        self,
        clinician_latency_params: dict[str, float],
        burn_windows: list[float],
        n_simulations: int = 10_000,
        rng_seed: int | None = None,
    ) -> list[dict[str, Any]]:
        """Compute expected CA-2 for each candidate burn window.

        Parameters
        ----------
        clinician_latency_params:
            Same as :meth:`find_minimum_burn_window`.
        burn_windows:
            Candidate windows in seconds.
        n_simulations:
            Monte-Carlo sample count.
        rng_seed:
            Optional reproducibility seed.

        Returns
        -------
        list[dict]
            One entry per burn window with ``burn_window_s``,
            ``burn_window_hours``, ``expected_ca2``,
            ``p05_latency_s``, ``p50_latency_s``, ``p95_latency_s``.
        """
        rng = np.random.default_rng(rng_seed)

        median_hours = clinician_latency_params.get("median_hours", 4.0)
        sigma = clinician_latency_params.get("sigma", 0.8)
        median_s = median_hours * 3600.0
        mu = np.log(median_s + _EPS)

        latencies = lognorm.rvs(s=sigma, scale=np.exp(mu), size=n_simulations, random_state=rng)
        p05 = float(np.percentile(latencies, 5))
        p50 = float(np.percentile(latencies, 50))
        p95 = float(np.percentile(latencies, 95))

        results: list[dict[str, Any]] = []
        for window_s in sorted(burn_windows):
            ca2 = float(np.mean(latencies < window_s))
            results.append({
                "burn_window_s": window_s,
                "burn_window_hours": window_s / 3600.0,
                "expected_ca2": round(ca2, 6),
                "p05_latency_s": round(p05, 1),
                "p50_latency_s": round(p50, 1),
                "p95_latency_s": round(p95, 1),
            })

        return results
