"""
Pacing decision-logic engine for VVI, DDD, and CRT-D modes.

Implements the full timing-cycle state machine used by modern CIEDs, including
AV-delay tracking, PVARP, upper-rate behaviour, mode switching, anti-tachycardia
pacing (ATP), and high-voltage shock delivery.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from enum import Enum
from typing import Any

import numpy as np
from numpy.random import Generator


# ---------------------------------------------------------------------------
# Public data-model types
# ---------------------------------------------------------------------------


class PacingMode(Enum):
    """Supported pacing modes."""

    VVI = "VVI"
    DDD = "DDD"
    CRT_D = "CRT_D"


@dataclass
class PacingParameters:
    """Programmable pacing parameters."""

    mode: PacingMode
    lower_rate_bpm: int = 60
    upper_rate_bpm: int = 130
    av_delay_sensed_ms: int = 150
    av_delay_paced_ms: int = 200
    pvarp_ms: int = 300
    vt_detection_rate_bpm: int = 180
    vf_detection_rate_bpm: int = 220
    rate_response_enabled: bool = True
    response_factor: int = 5  # 1-10 scale
    hysteresis_enabled: bool = False
    hysteresis_offset_bpm: int = 10
    vv_delay_ms: int = 0  # CRT only, -80 to +80


@dataclass
class PacingEvent:
    """A single pacing/sensing event generated by the engine."""

    timestamp_ms: float
    channel: str  # 'atrial', 'ventricular', 'lv', 'shock'
    event_type: str  # 'pace', 'sense', 'inhibit', 'atp', 'shock'
    amplitude_v: float = 0.0
    pulse_width_ms: float = 0.4


class _DDDState(Enum):
    """DDD timing-cycle states."""

    AS_VS = "AS_VS"
    AS_VP = "AS_VP"
    AP_VS = "AP_VS"
    AP_VP = "AP_VP"


# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------


class PacingEngine:
    """
    Pacing decision engine.

    Processes incoming cardiac events (sensed depolarisations) against
    programmed timing intervals and produces the appropriate pacing/inhibit
    output events.
    """

    def __init__(self, params: PacingParameters, rng: Generator | None = None) -> None:
        self._params = params
        self._rng: Generator = rng if rng is not None else np.random.default_rng()

        # --- timing state (ms) ---
        self._last_atrial_event_ms: float = -math.inf
        self._last_ventricular_event_ms: float = -math.inf
        self._last_lv_event_ms: float = -math.inf
        self._last_atrial_type: str = "pace"  # 'pace' or 'sense'
        self._last_ventricular_type: str = "pace"

        # DDD state
        self._ddd_state: _DDDState = _DDDState.AP_VP
        self._av_timer_started_ms: float = -math.inf
        self._av_timer_active: bool = False

        # Mode-switch tracking
        self._mode_switched: bool = False
        self._original_mode: PacingMode = params.mode
        self._mode_switch_count: int = 0

        # Statistics
        self._atrial_pace_count: int = 0
        self._atrial_sense_count: int = 0
        self._ventricular_pace_count: int = 0
        self._ventricular_sense_count: int = 0
        self._lv_pace_count: int = 0
        self._biv_pace_count: int = 0
        self._inhibit_count: int = 0
        self._atp_count: int = 0
        self._shock_count: int = 0
        self._total_events: int = 0

        # Therapy history
        self._therapy_log: list[PacingEvent] = []

    # -- Derived interval helpers ------------------------------------------

    @property
    def _lower_rate_interval_ms(self) -> float:
        """Lower-rate interval derived from lower_rate_bpm."""
        return 60_000.0 / self._params.lower_rate_bpm

    @property
    def _upper_rate_interval_ms(self) -> float:
        """Upper-rate interval derived from upper_rate_bpm."""
        return 60_000.0 / self._params.upper_rate_bpm

    @property
    def _hysteresis_interval_ms(self) -> float:
        """Escape interval when hysteresis is enabled (longer than LRI)."""
        effective_bpm = self._params.lower_rate_bpm - self._params.hysteresis_offset_bpm
        effective_bpm = max(effective_bpm, 30)
        return 60_000.0 / effective_bpm

    @property
    def _current_av_delay_ms(self) -> float:
        """AV delay based on whether the atrial event was sensed or paced."""
        if self._last_atrial_type == "sense":
            return float(self._params.av_delay_sensed_ms)
        return float(self._params.av_delay_paced_ms)

    def _vt_detection_interval_ms(self) -> float:
        return 60_000.0 / self._params.vt_detection_rate_bpm

    def _vf_detection_interval_ms(self) -> float:
        return 60_000.0 / self._params.vf_detection_rate_bpm

    # -- Core public API ---------------------------------------------------

    def process_cardiac_event(
        self,
        timestamp_ms: float,
        channel: str,
        amplitude_mv: float,
    ) -> list[PacingEvent]:
        """
        Process a single intrinsic cardiac event and return resulting
        pacing/inhibit events.

        Parameters
        ----------
        timestamp_ms:
            Absolute timestamp of the sensed event in milliseconds.
        channel:
            ``'atrial'`` or ``'ventricular'`` (or ``'lv'`` for CRT-D).
        amplitude_mv:
            Peak amplitude of the sensed signal in millivolts.

        Returns
        -------
        list[PacingEvent]
            Zero or more events produced by the pacing logic.
        """
        self._total_events += 1
        mode = self._params.mode

        if self._mode_switched:
            # During AT/AF mode-switch, operate in VVI-equivalent
            return self._process_vvi(timestamp_ms, channel, amplitude_mv)

        if mode == PacingMode.VVI:
            return self._process_vvi(timestamp_ms, channel, amplitude_mv)
        elif mode == PacingMode.DDD:
            return self._process_ddd(timestamp_ms, channel, amplitude_mv)
        elif mode == PacingMode.CRT_D:
            return self._process_crt_d(timestamp_ms, channel, amplitude_mv)
        return []

    # -- VVI ---------------------------------------------------------------

    def _process_vvi(
        self,
        timestamp_ms: float,
        channel: str,
        amplitude_mv: float,
    ) -> list[PacingEvent]:
        """
        VVI: pace ventricle if no sensed event within lower-rate interval.
        Inhibit on sense.
        """
        events: list[PacingEvent] = []

        if channel != "ventricular":
            # VVI ignores atrial events
            return events

        # Determine escape interval
        if self._params.hysteresis_enabled and self._last_ventricular_type == "sense":
            escape_ms = self._hysteresis_interval_ms
        else:
            escape_ms = self._lower_rate_interval_ms

        interval_since_last = timestamp_ms - self._last_ventricular_event_ms

        if amplitude_mv > 0 and interval_since_last < escape_ms:
            # Sensed within escape interval -> inhibit
            sense_event = PacingEvent(
                timestamp_ms=timestamp_ms,
                channel="ventricular",
                event_type="sense",
                amplitude_v=amplitude_mv / 1000.0,
            )
            inhibit_event = PacingEvent(
                timestamp_ms=timestamp_ms,
                channel="ventricular",
                event_type="inhibit",
            )
            events.extend([sense_event, inhibit_event])
            self._last_ventricular_event_ms = timestamp_ms
            self._last_ventricular_type = "sense"
            self._ventricular_sense_count += 1
            self._inhibit_count += 1
        else:
            # Escape interval expired -> pace
            pace_ts = max(
                timestamp_ms,
                self._last_ventricular_event_ms + escape_ms,
            )
            pace_event = PacingEvent(
                timestamp_ms=pace_ts,
                channel="ventricular",
                event_type="pace",
                amplitude_v=self._rng.uniform(2.5, 5.0),
                pulse_width_ms=0.4,
            )
            events.append(pace_event)
            self._last_ventricular_event_ms = pace_ts
            self._last_ventricular_type = "pace"
            self._ventricular_pace_count += 1

        return events

    # -- DDD ---------------------------------------------------------------

    def _process_ddd(
        self,
        timestamp_ms: float,
        channel: str,
        amplitude_mv: float,
    ) -> list[PacingEvent]:
        """
        DDD dual-chamber pacing with four timing states:
        AS-VS, AS-VP, AP-VS, AP-VP.
        """
        events: list[PacingEvent] = []

        if channel == "atrial":
            events.extend(self._ddd_atrial(timestamp_ms, amplitude_mv))
        elif channel == "ventricular":
            events.extend(self._ddd_ventricular(timestamp_ms, amplitude_mv))

        return events

    def _ddd_atrial(
        self,
        timestamp_ms: float,
        amplitude_mv: float,
    ) -> list[PacingEvent]:
        """Handle an atrial channel event in DDD mode."""
        events: list[PacingEvent] = []

        # Check PVARP -- if within PVARP of last ventricular event, ignore
        if (timestamp_ms - self._last_ventricular_event_ms) < self._params.pvarp_ms:
            return events

        # Determine if atrial sense or pace is needed
        escape_ms = self._lower_rate_interval_ms
        interval_since_last_atrial = timestamp_ms - self._last_atrial_event_ms

        if amplitude_mv > 0 and interval_since_last_atrial < escape_ms:
            # Atrial sense
            events.append(
                PacingEvent(
                    timestamp_ms=timestamp_ms,
                    channel="atrial",
                    event_type="sense",
                    amplitude_v=amplitude_mv / 1000.0,
                )
            )
            self._last_atrial_event_ms = timestamp_ms
            self._last_atrial_type = "sense"
            self._atrial_sense_count += 1
        else:
            # Atrial pace
            pace_ts = max(timestamp_ms, self._last_atrial_event_ms + escape_ms)
            events.append(
                PacingEvent(
                    timestamp_ms=pace_ts,
                    channel="atrial",
                    event_type="pace",
                    amplitude_v=self._rng.uniform(1.5, 3.5),
                    pulse_width_ms=0.4,
                )
            )
            self._last_atrial_event_ms = pace_ts
            self._last_atrial_type = "pace"
            self._atrial_pace_count += 1

        # Start AV timer
        self._av_timer_started_ms = self._last_atrial_event_ms
        self._av_timer_active = True

        return events

    def _ddd_ventricular(
        self,
        timestamp_ms: float,
        amplitude_mv: float,
    ) -> list[PacingEvent]:
        """Handle a ventricular channel event in DDD mode."""
        events: list[PacingEvent] = []
        av_delay = self._current_av_delay_ms

        if self._av_timer_active:
            elapsed_av = timestamp_ms - self._av_timer_started_ms

            if amplitude_mv > 0 and elapsed_av <= av_delay:
                # Ventricular sense within AV delay -> AS/AP-VS
                events.append(
                    PacingEvent(
                        timestamp_ms=timestamp_ms,
                        channel="ventricular",
                        event_type="sense",
                        amplitude_v=amplitude_mv / 1000.0,
                    )
                )
                self._last_ventricular_event_ms = timestamp_ms
                self._last_ventricular_type = "sense"
                self._ventricular_sense_count += 1
                self._av_timer_active = False

                # Update DDD state
                if self._last_atrial_type == "sense":
                    self._ddd_state = _DDDState.AS_VS
                else:
                    self._ddd_state = _DDDState.AP_VS
            elif elapsed_av >= av_delay:
                # AV delay expired -> ventricular pace (AS/AP-VP)
                # Enforce upper-rate limit
                interval_vv = (
                    self._av_timer_started_ms
                    + av_delay
                    - self._last_ventricular_event_ms
                )
                pace_ts = self._av_timer_started_ms + av_delay
                if interval_vv < self._upper_rate_interval_ms:
                    # Wenckebach-like upper-rate behaviour: extend AV delay
                    pace_ts = self._last_ventricular_event_ms + self._upper_rate_interval_ms

                events.append(
                    PacingEvent(
                        timestamp_ms=pace_ts,
                        channel="ventricular",
                        event_type="pace",
                        amplitude_v=self._rng.uniform(2.5, 5.0),
                        pulse_width_ms=0.4,
                    )
                )
                self._last_ventricular_event_ms = pace_ts
                self._last_ventricular_type = "pace"
                self._ventricular_pace_count += 1
                self._av_timer_active = False

                if self._last_atrial_type == "sense":
                    self._ddd_state = _DDDState.AS_VP
                else:
                    self._ddd_state = _DDDState.AP_VP
            else:
                # Within AV delay but no sense -- do nothing yet; wait for
                # either a sense or the timer to expire on a subsequent call.
                pass
        else:
            # No AV timer active -- ventricular escape
            escape_ms = self._lower_rate_interval_ms
            interval = timestamp_ms - self._last_ventricular_event_ms

            if amplitude_mv > 0 and interval < escape_ms:
                events.append(
                    PacingEvent(
                        timestamp_ms=timestamp_ms,
                        channel="ventricular",
                        event_type="sense",
                        amplitude_v=amplitude_mv / 1000.0,
                    )
                )
                self._last_ventricular_event_ms = timestamp_ms
                self._last_ventricular_type = "sense"
                self._ventricular_sense_count += 1
            else:
                pace_ts = max(
                    timestamp_ms,
                    self._last_ventricular_event_ms + escape_ms,
                )
                events.append(
                    PacingEvent(
                        timestamp_ms=pace_ts,
                        channel="ventricular",
                        event_type="pace",
                        amplitude_v=self._rng.uniform(2.5, 5.0),
                        pulse_width_ms=0.4,
                    )
                )
                self._last_ventricular_event_ms = pace_ts
                self._last_ventricular_type = "pace"
                self._ventricular_pace_count += 1

        return events

    # -- CRT-D -------------------------------------------------------------

    def _process_crt_d(
        self,
        timestamp_ms: float,
        channel: str,
        amplitude_mv: float,
    ) -> list[PacingEvent]:
        """
        CRT-D: biventricular pacing with VV delay offset plus VT/VF
        detection zones for ATP and shock therapy.
        """
        events: list[PacingEvent] = []

        # First run DDD-style atrial/RV logic
        if channel == "atrial":
            events.extend(self._ddd_atrial(timestamp_ms, amplitude_mv))
        elif channel == "ventricular":
            # Check for VT/VF detection zones
            vt_events = self._check_tachycardia_zones(timestamp_ms)
            if vt_events:
                events.extend(vt_events)
                return events

            rv_events = self._ddd_ventricular(timestamp_ms, amplitude_mv)
            events.extend(rv_events)

            # If RV was paced, also pace LV with VV delay offset
            for ev in rv_events:
                if ev.event_type == "pace" and ev.channel == "ventricular":
                    lv_events = self._pace_lv_biv(ev.timestamp_ms)
                    events.extend(lv_events)
        elif channel == "lv":
            # LV sense -- generally inhibit LV output
            events.append(
                PacingEvent(
                    timestamp_ms=timestamp_ms,
                    channel="lv",
                    event_type="sense",
                    amplitude_v=amplitude_mv / 1000.0,
                )
            )
            self._last_lv_event_ms = timestamp_ms

        return events

    def _pace_lv_biv(self, rv_pace_ts_ms: float) -> list[PacingEvent]:
        """
        Deliver biventricular LV pace offset from the RV pace by vv_delay_ms.

        Positive VV delay: LV paced *after* RV.
        Negative VV delay: LV paced *before* RV (pre-excitation).
        """
        events: list[PacingEvent] = []
        vv_delay = float(self._params.vv_delay_ms)
        lv_ts = rv_pace_ts_ms + vv_delay

        events.append(
            PacingEvent(
                timestamp_ms=lv_ts,
                channel="lv",
                event_type="pace",
                amplitude_v=self._rng.uniform(2.5, 5.0),
                pulse_width_ms=0.5,
            )
        )
        self._last_lv_event_ms = lv_ts
        self._lv_pace_count += 1
        self._biv_pace_count += 1
        return events

    def _check_tachycardia_zones(self, timestamp_ms: float) -> list[PacingEvent]:
        """
        Check if the current ventricular rate falls within VT or VF
        detection zones. Returns therapy events if triggered.
        """
        interval_ms = timestamp_ms - self._last_ventricular_event_ms
        if interval_ms <= 0:
            return []

        events: list[PacingEvent] = []
        vf_interval = self._vf_detection_interval_ms()
        vt_interval = self._vt_detection_interval_ms()

        if 0 < interval_ms <= vf_interval:
            # VF zone -> immediate shock
            events.append(
                self.deliver_shock(energy_joules=35.0)
            )
        elif 0 < interval_ms <= vt_interval:
            # VT zone -> ATP first
            events.extend(self.deliver_atp(vt_cycle_length_ms=interval_ms))

        return events

    # -- Mode switch -------------------------------------------------------

    def trigger_mode_switch(self, to_mode: str) -> None:
        """
        Activate an AT/AF-triggered mode switch.

        Typically switches DDD/CRT-D to a VVI/VVIR equivalent to avoid
        tracking high atrial rates.

        Parameters
        ----------
        to_mode:
            Target mode string (e.g. ``'VVI'``). The engine falls back
            to VVI-equivalent logic while mode-switched.
        """
        if not self._mode_switched:
            self._mode_switched = True
            self._mode_switch_count += 1

    def revert_mode_switch(self) -> None:
        """Revert from mode-switch back to the original programmed mode."""
        self._mode_switched = False

    # -- Therapies ---------------------------------------------------------

    def deliver_atp(self, vt_cycle_length_ms: float) -> list[PacingEvent]:
        """
        Deliver anti-tachycardia pacing: 8 pulses at 88 % of the
        detected VT cycle length.

        Parameters
        ----------
        vt_cycle_length_ms:
            Measured VT cycle length in milliseconds.

        Returns
        -------
        list[PacingEvent]
            Sequence of 8 ATP stimulus events.
        """
        events: list[PacingEvent] = []
        atp_cl_ms = vt_cycle_length_ms * 0.88
        base_ts = self._last_ventricular_event_ms

        for i in range(8):
            ts = base_ts + atp_cl_ms * (i + 1)
            events.append(
                PacingEvent(
                    timestamp_ms=ts,
                    channel="ventricular",
                    event_type="atp",
                    amplitude_v=self._rng.uniform(5.0, 7.5),
                    pulse_width_ms=1.0,
                )
            )

        self._atp_count += 1
        self._therapy_log.extend(events)

        # Update ventricular timing reference
        if events:
            self._last_ventricular_event_ms = events[-1].timestamp_ms
            self._last_ventricular_type = "pace"

        return events

    def deliver_shock(self, energy_joules: float) -> PacingEvent:
        """
        Deliver a high-voltage shock therapy.

        Parameters
        ----------
        energy_joules:
            Shock energy in joules (typically 10-41 J).

        Returns
        -------
        PacingEvent
            The shock event.
        """
        # Capacitor charge time ~5-12 seconds
        charge_time_ms = self._rng.uniform(5000.0, 12000.0)
        shock_ts = self._last_ventricular_event_ms + charge_time_ms

        shock_event = PacingEvent(
            timestamp_ms=shock_ts,
            channel="shock",
            event_type="shock",
            amplitude_v=energy_joules * 22.0,  # ~750-800V for 35J
            pulse_width_ms=12.0,
        )
        self._shock_count += 1
        self._therapy_log.append(shock_event)
        self._last_ventricular_event_ms = shock_ts
        self._last_ventricular_type = "pace"
        return shock_event

    # -- Statistics --------------------------------------------------------

    def get_pacing_statistics(self) -> dict[str, Any]:
        """
        Return summary statistics for the pacing session.

        Returns
        -------
        dict
            Keys include pacing percentages per chamber, mode-switch counts,
            and therapy delivery counts.
        """
        total_atrial = self._atrial_pace_count + self._atrial_sense_count
        total_ventricular = self._ventricular_pace_count + self._ventricular_sense_count

        atrial_pacing_pct = (
            (self._atrial_pace_count / total_atrial * 100.0) if total_atrial > 0 else 0.0
        )
        ventricular_pacing_pct = (
            (self._ventricular_pace_count / total_ventricular * 100.0)
            if total_ventricular > 0
            else 0.0
        )

        # BiV pacing percentage: fraction of ventricular paces that were BiV
        biv_pacing_pct = (
            (self._biv_pace_count / self._ventricular_pace_count * 100.0)
            if self._ventricular_pace_count > 0
            else 0.0
        )

        return {
            "mode": self._params.mode.value,
            "mode_switched": self._mode_switched,
            "mode_switch_count": self._mode_switch_count,
            "atrial_pace_count": self._atrial_pace_count,
            "atrial_sense_count": self._atrial_sense_count,
            "atrial_pacing_pct": round(atrial_pacing_pct, 1),
            "ventricular_pace_count": self._ventricular_pace_count,
            "ventricular_sense_count": self._ventricular_sense_count,
            "ventricular_pacing_pct": round(ventricular_pacing_pct, 1),
            "lv_pace_count": self._lv_pace_count,
            "biventricular_pace_count": self._biv_pace_count,
            "biventricular_pacing_pct": round(biv_pacing_pct, 1),
            "inhibit_count": self._inhibit_count,
            "atp_therapy_count": self._atp_count,
            "shock_therapy_count": self._shock_count,
            "total_events_processed": self._total_events,
            "ddd_state": self._ddd_state.value if self._params.mode != PacingMode.VVI else None,
        }
